"""The labelled corpus the validation harness measures against.

**What a corpus is here, and what it deliberately is not.** It is a list of
labelled examples with a *declared provenance*, split into a calibration half
and a held-out half by a rule that does not depend on file order. It is not a
training set — nothing in this phase learns weights — and it is not a fixture:
a fixture exists to make a test pass, while this exists to produce a number that
is allowed to be disappointing.

**Why provenance is a required field on every example rather than a note in the
README.** The phase gate asks for "a published per-category F1 number", and the
single most misleading thing this repository could ship is a good-looking F1
measured on inputs that were generated by the same intuition that wrote the
prompts. So every example declares where it came from, the report groups the
numbers by that declaration, and a reader can never mistake an authored sentence
for a citizen's. The three values are deliberately few:

``authored``
    Written by the team, in the language a citizen would use, from the defect
    descriptions in §8. Genuinely exercises the text encoder — a Marathi
    sentence embedded by multilingual-e5 is a real measurement of that model on
    that language — and genuinely does not exercise the distribution shift a
    real intake queue has. Both halves of that are stated in the report.
``field``
    Real submissions, labelled by a human. None exist yet; the loader accepts
    them the day they do, which is the point of having the value now rather
    than adding it later and re-cutting every number for comparability.
``synthetic``
    Procedurally generated pixels with ground truth this module computed. Used
    for exactly one measurement — the distant-face recall curve — where the
    question is *geometric* ("does a two-metre detector find a fourteen-pixel
    face") rather than semantic, and a controlled stimulus is the right
    instrument rather than a compromise.

**The split is stratified inside this module and nowhere else.** A held-out set
chosen by ``examples[:n]`` inherits whatever order the file was written in, and
the author wrote the easy ones first — everybody does. Stratifying by (category,
locale) and ordering within a stratum by a hash of the example id means every
category and every language appears on both sides, the assignment is stable
across edits to unrelated examples, and it is reproducible from the corpus file
alone with no seed to lose.
"""

from __future__ import annotations

import hashlib
import json
import math
from collections.abc import Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Any, Final

#: Where the committed corpora live. A directory rather than one file because a
#: tenant shape is a corpus: the categories a municipality reports are not the
#: categories a campus reports, and one file listing both would measure a
#: taxonomy no deployment has.
CORPUS_DIR: Final = Path(__file__).resolve().parent / "corpora"
CORPUS_SUFFIX: Final = ".json"

#: Fraction of each stratum reserved for fitting the calibration curves. A third
#: rather than a half: the published number is the held-out one, and the
#: calibration fit needs enough examples per category to be worth doing but not
#: at the cost of the measurement it exists to serve.
DEFAULT_CALIBRATION_FRACTION: Final = 1.0 / 3.0


class Provenance(StrEnum):
    """Where an example came from. See the module docstring on why this exists."""

    AUTHORED = "authored"
    FIELD = "field"
    SYNTHETIC = "synthetic"


class Split(StrEnum):
    CALIBRATION = "calibration"
    HOLDOUT = "holdout"


class CorpusError(Exception):
    """A corpus file cannot be used as a measurement instrument.

    Raised rather than repaired. Every failure here — a duplicate id, a label
    naming a category the taxonomy does not have, a stratum with one example in
    it — produces a *number* if it is tolerated, and a number produced from a
    broken instrument is worse than no number, because it is quotable.
    """


@dataclass(frozen=True, slots=True)
class Example:
    """One labelled item.

    ``text`` and ``image`` are both optional and at least one is required: a
    text-only example measures the text tower, an image-only example measures
    CLIP, and one carrying both measures the fusion rule. The corpus does not
    have to be homogeneous and saying so in the type is cheaper than a
    convention nobody reads.

    ``image`` is a *path relative to the corpus file's directory*, never an
    absolute one — a corpus is a checked-in artefact and an absolute path in it
    is a corpus that only reproduces on the machine that wrote it.
    """

    id: str
    category: str
    locale: str
    provenance: Provenance
    text: str | None = None
    image: str | None = None
    note: str = ""

    def __post_init__(self) -> None:
        if not self.text and not self.image:
            raise CorpusError(
                f"example {self.id!r} carries neither text nor an image, so there is "
                f"nothing to classify and it would count as a miss against whichever "
                f"category it claims to be"
            )

    @property
    def stratum(self) -> tuple[str, str]:
        """What the split is balanced across: the label and the language.

        Both, not just the label. A held-out set that happened to put every
        Marathi example on one side would produce a per-category F1 that is
        really a per-language F1 wearing a category's name, and the failure is
        invisible from the number.
        """
        return (self.category, self.locale)


@dataclass(frozen=True, slots=True)
class Corpus:
    """A named, versioned set of labelled examples with one taxonomy in mind."""

    corpus_id: str
    template: str
    description: str
    authored: str
    root: Path
    examples: tuple[Example, ...]

    @property
    def categories(self) -> tuple[str, ...]:
        return tuple(sorted({example.category for example in self.examples}))

    @property
    def locales(self) -> tuple[str, ...]:
        return tuple(sorted({example.locale for example in self.examples}))

    @property
    def provenances(self) -> tuple[str, ...]:
        return tuple(sorted({example.provenance.value for example in self.examples}))

    def image_path(self, example: Example) -> Path:
        if example.image is None:  # pragma: no cover - guarded by the caller
            raise CorpusError(f"example {example.id!r} has no image")
        return (self.root / example.image).resolve()

    def counts(self) -> dict[tuple[str, str], int]:
        counts: dict[tuple[str, str], int] = {}
        for example in self.examples:
            counts[example.stratum] = counts.get(example.stratum, 0) + 1
        return counts

    def split(
        self, *, calibration_fraction: float = DEFAULT_CALIBRATION_FRACTION
    ) -> tuple[tuple[Example, ...], tuple[Example, ...]]:
        """``(calibration, holdout)``, stratified by (category, locale).

        Deterministic from the corpus file alone: within each stratum the
        examples are ordered by ``sha256(corpus_id + example id)`` and the first
        ``ceil(n * fraction)`` go to calibration. No seed, because a seed is one
        more thing that has to travel with the report for the number to be
        reproducible, and it is the thing most likely not to.

        ``ceil`` rather than ``round`` so a stratum of two contributes one to
        each side rather than zero to calibration. A stratum of one is refused
        by ``load`` — see ``_validate`` — because it cannot appear on both sides
        and silently appearing on neither is how a category disappears from a
        report that still claims to cover it.
        """
        if not 0.0 < calibration_fraction < 1.0:
            raise CorpusError(
                f"calibration_fraction must be strictly between 0 and 1; {calibration_fraction} "
                f"would leave one of the two halves empty and the report would be measuring "
                f"the set it was fitted on"
            )
        calibration: list[Example] = []
        holdout: list[Example] = []
        for _, members in sorted(self._by_stratum().items()):
            ordered = sorted(members, key=lambda item: self._rank(item))
            cut = math.ceil(len(ordered) * calibration_fraction)
            calibration.extend(ordered[:cut])
            holdout.extend(ordered[cut:])
        return tuple(calibration), tuple(holdout)

    def _by_stratum(self) -> dict[tuple[str, str], list[Example]]:
        grouped: dict[tuple[str, str], list[Example]] = {}
        for example in self.examples:
            grouped.setdefault(example.stratum, []).append(example)
        return grouped

    def _rank(self, example: Example) -> str:
        return hashlib.sha256(f"{self.corpus_id}\x00{example.id}".encode()).hexdigest()

    def fingerprint(self) -> str:
        """A hash over everything a measurement depends on.

        Written into the report so a number and the corpus that produced it can
        be checked against each other later. Covers the labels and the inputs
        and nothing else — not ``description``, not ``authored`` — because a
        typo fixed in the prose does not invalidate a measurement and a
        fingerprint that says it does is a fingerprint people learn to ignore.
        """
        digest = hashlib.sha256()
        digest.update(f"{self.corpus_id}\x00".encode())
        for example in sorted(self.examples, key=lambda item: item.id):
            digest.update(
                "\x01".join(
                    (
                        example.id,
                        example.category,
                        example.locale,
                        example.provenance.value,
                        example.text or "",
                        example.image or "",
                    )
                ).encode()
            )
            digest.update(b"\x02")
        return digest.hexdigest()


def load(corpus_id: str, *, directory: Path | None = None) -> Corpus:
    """Read and validate one corpus by id."""
    root = directory if directory is not None else CORPUS_DIR
    path = root / f"{corpus_id}{CORPUS_SUFFIX}"
    if not path.is_file():
        available = ", ".join(sorted(item.stem for item in root.glob(f"*{CORPUS_SUFFIX}")))
        raise CorpusError(
            f"no corpus named {corpus_id!r} in {root}; available: {available or '(none)'}"
        )
    return loads(path.read_text(encoding="utf-8"), root=path.parent)


def loads(raw: str, *, root: Path) -> Corpus:
    """Parse a corpus document. ``root`` is what image paths resolve against."""
    try:
        document: Mapping[str, Any] = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise CorpusError(f"the corpus file is not valid JSON: {exc}") from exc

    try:
        examples = tuple(_example(entry) for entry in document["examples"])
        corpus = Corpus(
            corpus_id=str(document["corpus_id"]),
            template=str(document["template"]),
            description=str(document["description"]),
            authored=str(document["authored"]),
            root=root,
            examples=examples,
        )
    except KeyError as exc:
        raise CorpusError(f"the corpus file is missing a required key: {exc}") from exc

    _validate(corpus)
    return corpus


def _example(entry: Mapping[str, Any]) -> Example:
    try:
        provenance = Provenance(str(entry.get("provenance", Provenance.AUTHORED.value)))
    except ValueError as exc:
        raise CorpusError(
            f"example {entry.get('id')!r} declares provenance "
            f"{entry.get('provenance')!r}, which is not one of "
            f"{', '.join(item.value for item in Provenance)}"
        ) from exc
    return Example(
        id=str(entry["id"]),
        category=str(entry["category"]),
        locale=str(entry["locale"]),
        provenance=provenance,
        text=(str(entry["text"]) if entry.get("text") else None),
        image=(str(entry["image"]) if entry.get("image") else None),
        note=str(entry.get("note", "")),
    )


#: Fewest examples a (category, locale) stratum may carry. Two, because that is
#: the smallest number that can be present on both sides of the split — and a
#: category present only in the calibration half is one the published F1 does
#: not cover while the report's category list says it does.
MIN_STRATUM_SIZE: Final = 2


def _validate(corpus: Corpus) -> None:
    seen: set[str] = set()
    duplicates: set[str] = set()
    for example in corpus.examples:
        if example.id in seen:
            duplicates.add(example.id)
        seen.add(example.id)
    if duplicates:
        raise CorpusError(
            f"duplicate example id(s): {', '.join(sorted(duplicates))}. Ids key the split, so a "
            f"duplicate would put the same example on both sides of it"
        )
    if not corpus.examples:
        raise CorpusError("the corpus is empty; there is nothing to measure")

    thin = sorted(
        f"{category}/{locale} ({count})"
        for (category, locale), count in corpus.counts().items()
        if count < MIN_STRATUM_SIZE
    )
    if thin:
        raise CorpusError(
            f"stratum too small to appear on both sides of the split: {', '.join(thin)}. "
            f"Either add examples or drop the stratum — a category that reaches the "
            f"report with no held-out examples produces an F1 of zero that says nothing "
            f"about the model"
        )


def only(examples: Iterable[Example], *, provenance: Provenance) -> tuple[Example, ...]:
    """The subset with one provenance, for the per-provenance report sections."""
    return tuple(example for example in examples if example.provenance is provenance)


def with_text(examples: Iterable[Example]) -> tuple[Example, ...]:
    return tuple(example for example in examples if example.text)


def with_images(examples: Iterable[Example]) -> tuple[Example, ...]:
    return tuple(example for example in examples if example.image)


def available() -> tuple[str, ...]:
    return tuple(sorted(path.stem for path in CORPUS_DIR.glob(f"*{CORPUS_SUFFIX}")))


# ---------------------------------------------------------------------------
# The one place synthetic pixels are legitimate: the face-scale stimulus
# ---------------------------------------------------------------------------
#
# §22.1 protects bystanders, and the bystanders in street photography are small.
# ``blaze_face_short_range`` is documented as a two-metre model, and the honest
# question is not "does it find faces" but "at what pixel size does it stop".
# That is a question about scale, and the instrument for a question about scale
# is a stimulus whose scale is a parameter — not a photograph whose face size is
# whatever the photographer stood at.
#
# The stimulus is deliberately the same crude frontal face the Phase 8 gate
# submits, for one reason worth stating: that face is already known to fire the
# real MediaPipe detector in the real container, so a zero at some size is a
# fact about the size rather than about the drawing. What this measurement does
# *not* establish is absolute recall on real bystanders, and the report says so
# in those words rather than in a footnote.


@dataclass(frozen=True, slots=True)
class FaceStimulus:
    """One rendered scene and the ground truth that came with it."""

    face_pixels: int
    width: int
    height: int
    #: (x, y, w, h) of every face drawn, in pixels, origin top-left.
    boxes: tuple[tuple[int, int, int, int], ...]
    rgb: bytes

    @property
    def face_count(self) -> int:
        return len(self.boxes)


#: Face widths in pixels, in the scene. Spans the range that matters: a 96 px
#: face is somebody photographed deliberately, a 24 px face is a bystander eight
#: metres away, and 12 px is the edge of what any detector can be asked for.
#:
#: Sampled tightly between 64 and 96 on purpose. The first run of this curve put
#: the whole transition inside that gap — nothing found at 64, everything found
#: at 96 — and a measurement whose only interesting region is the one it did not
#: sample is a measurement that has to be run again. The extra four points cost
#: sixteen detector calls.
FACE_PIXEL_SIZES: Final[tuple[int, ...]] = (
    12,
    16,
    24,
    32,
    48,
    64,
    72,
    80,
    88,
    96,
    128,
)

#: Scene size. Fixed rather than scaled with the face, because a detector that
#: is scale-invariant would be indistinguishable from one that is not if the
#: face always filled the same fraction of the frame — which is exactly the
#: mistake a naive version of this measurement makes.
SCENE_WIDTH: Final = 640
SCENE_HEIGHT: Final = 480


def face_stimulus(face_pixels: int, *, seed: int = 0, faces: int = 1) -> FaceStimulus:
    """A street-ish scene with ``faces`` frontal faces ``face_pixels`` wide.

    Returns raw RGB rather than an encoded image because the detector protocol
    takes ``(width, height, rgb)`` — encoding to PNG here would mean the
    measurement passed through a codec that the redaction path does not use for
    this input, and any difference it made would be attributed to the detector.
    """
    if face_pixels < 4:
        raise CorpusError("a face smaller than four pixels is not a stimulus, it is noise")

    width, height = SCENE_WIDTH, SCENE_HEIGHT
    pixels = bytearray(width * height * 3)
    # A flat gradient background rather than a solid colour: a uniform field is
    # not a street, and a detector's non-maximum suppression behaves differently
    # against texture than against nothing at all.
    for y in range(height):
        for x in range(width):
            offset = (y * width + x) * 3
            pixels[offset] = (70 + (x * 7 + seed * 13) // 11) % 200
            pixels[offset + 1] = (90 + (y * 5) // 7) % 200
            pixels[offset + 2] = (120 + (x + y) // 9) % 220

    boxes: list[tuple[int, int, int, int]] = []
    face_height = round(face_pixels * 1.3)
    for index in range(faces):
        # Spread across the frame, deterministically, and kept clear of the
        # edges: a face clipped by the frame is a different measurement (partial
        # occlusion) wearing this one's name.
        slot = (index + 1) / (faces + 1)
        cx = int(width * slot)
        cy = height // 2 + ((index % 3) - 1) * (height // 6)
        left = cx - face_pixels // 2
        top = cy - face_height // 2
        _draw_face(pixels, width, height, left=left, top=top, w=face_pixels, h=face_height)
        boxes.append((left, top, face_pixels, face_height))

    return FaceStimulus(
        face_pixels=face_pixels,
        width=width,
        height=height,
        boxes=tuple(boxes),
        rgb=bytes(pixels),
    )


def _draw_face(
    pixels: bytearray, width: int, height: int, *, left: int, top: int, w: int, h: int
) -> None:
    """A crude frontal face: skin ellipse, two eyes, a nose, a mouth.

    Written out in arithmetic rather than drawn with Pillow so this module has
    no image-library dependency at all — it runs in the harness, which runs in
    ``worker-ml``, and it also runs in the test suite, which runs in ``api``.
    """
    cx, cy = left + w / 2.0, top + h / 2.0
    rx, ry = w / 2.0, h / 2.0
    eye_r = max(1.0, w * 0.09)
    for y in range(max(0, top), min(height, top + h)):
        for x in range(max(0, left), min(width, left + w)):
            dx, dy = (x - cx) / rx, (y - cy) / ry
            if dx * dx + dy * dy > 1.0:
                continue
            offset = (y * width + x) * 3
            red, green, blue = 233, 190, 158
            for eye_x in (cx - w * 0.22, cx + w * 0.22):
                if (x - eye_x) ** 2 + (y - (cy - h * 0.15)) ** 2 <= eye_r * eye_r:
                    red, green, blue = 32, 28, 26
            if abs(x - cx) < w * 0.18 and abs(y - (cy + h * 0.28)) < max(1.0, h * 0.05):
                red, green, blue = 150, 62, 58
            if abs(x - cx) < max(1.0, w * 0.05) and abs(y - (cy + h * 0.05)) < h * 0.14:
                red, green, blue = 206, 162, 132
            pixels[offset], pixels[offset + 1], pixels[offset + 2] = red, green, blue


def face_stimuli(
    sizes: Sequence[int] = FACE_PIXEL_SIZES, *, repeats: int = 4, faces: int = 1
) -> Iterator[FaceStimulus]:
    """One stimulus per (size, repeat). ``repeats`` shifts the background only.

    The face itself is identical across repeats by construction — the point is
    to give the detector several attempts at the same scale against different
    surroundings, so a single unlucky background does not become the recall
    number for that size.
    """
    for size in sizes:
        for index in range(repeats):
            yield face_stimulus(size, seed=index, faces=faces)


__all__ = [
    "CORPUS_DIR",
    "DEFAULT_CALIBRATION_FRACTION",
    "FACE_PIXEL_SIZES",
    "MIN_STRATUM_SIZE",
    "SCENE_HEIGHT",
    "SCENE_WIDTH",
    "Corpus",
    "CorpusError",
    "Example",
    "FaceStimulus",
    "Provenance",
    "Split",
    "available",
    "face_stimuli",
    "face_stimulus",
    "load",
    "loads",
    "only",
    "with_images",
    "with_text",
]
