"use client";

import { useState } from "react";

import type { Complaint } from "@/lib/api/complaints";
import { plural, t, type Strings } from "@/lib/i18n/strings";

import "./citizen.css";

/**
 * §E17.2's payoff — the one sentence that changes what reporting feels like.
 *
 * > **You're the 4th person to report this.** First reported 6 days ago.
 * > Severity raised to *High.*
 * >
 * > One sentence that converts a solitary act into a collective one — and it is
 * > generated by the real dedup engine, not written by a copywriter.
 *
 * **Every number is read from the projection, not from the stream.**
 * `cluster_report_count` and `cluster_first_reported` are on
 * `GET /complaints/{id}`, published for exactly this sentence. The obvious
 * alternative — read `report_count` off `cluster_match_found` as it arrives on
 * the socket — is what §E14.3 forbids: *"the WebSocket is a hint, not a source
 * of truth"*, and `store.ts` says of its own buffer that *"nothing renders a
 * fact from it"*. A citizen being told they are the fourth person is being told
 * a fact.
 *
 * **It renders nothing until the engine has spoken.** A report the dedup stage
 * has not reached yet has `cluster_report_count === null`, and the honest
 * rendering of that is no sentence at all — not *"you're the 1st person"*,
 * which is a claim about the city that nothing has checked. §E3.3.
 *
 * **The ordinal is a plural rule, not a suffix table.** `Intl.PluralRules` per
 * locale: Marathi and Hindi do not partition the way English does, and a
 * hand-rolled `n === 1` check is how a civic product ends up telling somebody
 * they are the *"1 people"* to report a pothole.
 */
export function DedupPayoff({
  complaint,
  strings,
  now,
}: {
  readonly complaint: Complaint;
  readonly strings: Strings;
  /** Injected so a golden image and a test are not functions of the clock. */
  readonly now?: number;
}) {
  /*
   * A clock read once, in a lazy initialiser, rather than on every render.
   *
   * Two reasons and the second is the real one. `Date.now()` during render is
   * impure — React may render this component twice for one paint and get two
   * answers. And *"first reported 6 days ago"* should not silently become
   * *"7 days ago"* because an unrelated state change happened to re-render the
   * card at midnight. A sentence a citizen is asked to believe should be stable
   * for as long as they are looking at it.
   */
  const [renderedAt] = useState(() => Date.now());
  const at = now ?? renderedAt;

  const count = complaint.cluster_report_count;
  if (count === null || count === undefined) return null;

  // A cluster of one is not a payoff, it is the ordinary case, and dressing it
  // up as one would make the sentence meaningless the first time it was true.
  if (count <= 1) {
    return (
      <p className="dedup-payoff" data-shape="first">
        <span className="dedup-payoff__lead type-heading">{t(strings, "dedup.first")}</span>
      </p>
    );
  }

  const firstReported = complaint.cluster_first_reported;
  const days =
    firstReported === undefined || firstReported === null ? null : daysSince(firstReported, at);

  return (
    <p className="dedup-payoff" data-shape="joined">
      <span className="dedup-payoff__lead type-heading">{plural(strings, "dedup.nth", count)}</span>
      {days === null ? null : (
        <span className="dedup-payoff__since type-body">
          {days === 0
            ? t(strings, "dedup.firstReportedToday")
            : plural(strings, "dedup.firstReportedDays", days)}
        </span>
      )}
    </p>
  );
}

/**
 * Whole days, floored, from an RFC 3339 timestamp.
 *
 * Floored rather than rounded: *"first reported 6 days ago"* about something 6.7
 * days old is true, and about something 5.6 days old is not. On a sentence whose
 * whole purpose is to be believed, the direction of the error matters more than
 * its size.
 */
function daysSince(timestamp: string, now: number): number | null {
  const then = Date.parse(timestamp);
  if (Number.isNaN(then)) return null;
  return Math.max(0, Math.floor((now - then) / 86_400_000));
}
