/**
 * The generated client — §E15, §E24, and execution-plan **Law 2**.
 *
 * > Fixtures are generated, never invented. Where a phase has not landed, its
 * > screens are built against the **real generated types** … with fixture
 * > *values*, never a fixture *shape*. A hand-written interface describing a
 * > backend contract is a review failure; if the type does not exist yet, the
 * > screen is not ready to build.  — §E24
 *
 * The source is `backend/nemesis/api/openapi.json`, which the backend writes
 * with `nem web-openapi` and commits alongside `api_contract_lock.json` and
 * `events/schema_lock.json`. Committing the schema rather than fetching it at
 * build time is what makes drift *visible*: the client cannot silently
 * regenerate against a server that changed, because the schema change shows up
 * in the same pull request as the backend change that caused it.
 *
 * `--check` regenerates into memory and diffs. §E15's Phase 18 gate is
 * "generated-client drift fails CI", and this is that gate.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString, type OpenAPI3 } from "openapi-typescript";
import { format } from "prettier";

const ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const SCHEMA = join(ROOT, "..", "backend", "nemesis", "api", "openapi.json");
const OUT = join(ROOT, "src", "generated", "api.ts");

const BANNER = `/**
 * GENERATED by scripts/generate-api-types.ts from
 * backend/nemesis/api/openapi.json. Do not edit.
 *
 * §E24, Law 2 — a hand-written interface describing a backend contract is a
 * review failure. If a type you need is not in this file, the endpoint does not
 * publish it yet, and the screen that needs it is not ready to build. Fix the
 * backend's contract, re-run \`nem web-openapi\` and \`nem web-types\`, and
 * commit all three together.
 */

/* eslint-disable @typescript-eslint/no-empty-object-type */

`;

async function build(): Promise<string> {
  const schema = JSON.parse(readFileSync(SCHEMA, "utf8")) as OpenAPI3;
  const ast = await openapiTS(schema, {
    // `null` where the schema says nullable, rather than `undefined`. The
    // backend returns explicit nulls for the fields whose phase has not landed
    // — `severity_score` is null today, not absent — and §E24's whole point is
    // that a screen renders that null honestly rather than pretending the field
    // does not exist.
    emptyObjectsUnknown: true,
    defaultNonNullable: false,
  });
  return BANNER + astToString(ast);
}

const ENUMS_OUT = join(ROOT, "src", "generated", "enums.ts");

interface StringEnumSchema {
  readonly type?: string;
  readonly enum?: readonly string[];
  readonly description?: string;
}

/** SCREAMING_SNAKE plural for a PascalCase schema name. */
function constantName(schema: string): string {
  const snake = schema.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
  return snake.endsWith("S") ? `${snake}ES` : `${snake}S`;
}

/**
 * Runtime arrays for the schema's string enums.
 *
 * `openapi-typescript` emits a union *type*, which is exactly right for
 * checking a value and useless for iterating one. §E26.1 needs both: a status
 * chip must fail to compile when a member is added (the union), and a Storybook
 * matrix or a filter control must be able to enumerate every member without
 * anyone typing the list a second time (the array).
 *
 * Typing the list a second time is the failure mode §E2 defect #16 describes —
 * *"the status vocabulary was never written down anywhere … every surface
 * invents its own status chips"* — so it is generated here instead.
 */
function buildEnums(schema: Record<string, unknown>): string {
  const components = schema["components"] as { schemas?: Record<string, StringEnumSchema> };
  const schemas = components.schemas ?? {};

  const lines = [
    `/**
 * GENERATED by scripts/generate-api-types.ts from
 * backend/nemesis/api/openapi.json. Do not edit.
 *
 * Runtime companions to the union types in ./api.ts — §E26.1. A view that
 * omits a member of one of these sets is a defect, including the members that
 * only occur when something has gone wrong, which are the ones a UI is most
 * likely to forget and most needs to show.
 */

import type { components } from "./api";
`,
  ];

  for (const [name, definition] of Object.entries(schemas)) {
    if (definition.type !== "string" || !Array.isArray(definition.enum)) continue;
    const values = definition.enum;
    if (definition.description) {
      lines.push(`/** ${definition.description.replace(/\*\//g, "*\\/")} */`);
    }
    lines.push(
      `export const ${constantName(name)} = ${JSON.stringify(values)} as const satisfies readonly components["schemas"]["${name}"][];`,
      `export type ${name} = components["schemas"]["${name}"];`,
      "",
    );
  }

  return lines.join("\n");
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const schema = JSON.parse(readFileSync(SCHEMA, "utf8")) as Record<string, unknown>;

  const artefacts = [
    { path: OUT, body: await build(), label: "./src/generated/api.ts" },
    { path: ENUMS_OUT, body: buildEnums(schema), label: "./src/generated/enums.ts" },
  ];

  let stale = 0;
  for (const artefact of artefacts) {
    const generated = await format(artefact.body, { parser: "typescript", printWidth: 100 });

    if (!check) {
      writeFileSync(artefact.path, generated, "utf8");
      console.log(`  wrote ${artefact.label}`);
      continue;
    }

    let current: string | null = null;
    try {
      current = readFileSync(artefact.path, "utf8");
    } catch {
      current = null;
    }
    if (current !== generated) {
      stale += 1;
      console.error(`✗ stale: ${artefact.label}`);
    }
  }

  if (check) {
    if (stale > 0) {
      console.error(
        "\napi types: the generated client does not match backend/nemesis/api/openapi.json.\n" +
          "  Run `nem web-types`. A client that type-checks against a contract the\n" +
          "  server stopped serving is worse than no types at all — it is confident\n" +
          "  and wrong, which is the failure §E14.3 spends a whole section avoiding.",
      );
      process.exitCode = 1;
      return;
    }
    console.log("api types: generated client matches the schema");
  }
}

await main();
