"""Phase 5 — tenant, taxonomy & organisation service (control plane).

Revision ID: dbd7ca971688
Revises: 69df6db2b72e
Create Date: 2026-08-17 10:50:55.960780

Seven new tables and three altered ones. Three things in here were **not**
autogenerated and are the reason this file was rewritten by hand:

1. **``geoalchemy2`` is imported explicitly.** Autogenerate emits
   ``geoalchemy2.types.Geography(...)`` and does not add the import, so the
   generated file raises ``NameError`` the first time it runs. Silent until
   somebody migrates a fresh database, which is every CI run and every new
   developer.

2. **``departments.path`` is added nullable, backfilled, then made NOT NULL.**
   Autogenerate emits a single ``NOT NULL`` ``add_column`` with no server
   default, which fails on any table that already has rows — that is every
   deployment that has onboarded a customer. The backfill sets ``path = code``
   and ``depth = 0``, which is correct because every existing department is a
   root: ``parent_id`` was nullable and nothing before this migration wrote it.
   The single-statement recursive rebuild is deliberately not attempted; if a
   future migration inherits a populated tree, ``control_plane.organisation``
   is where the rebuild belongs, with a test.

3. **``contractors.categories_certified`` is dropped, and the data it held
   cannot be carried forward.** The column stored taxonomy *keys*, and
   ``contractor_certifications`` references ``taxonomy_nodes.id`` — but
   ``taxonomy_nodes`` is created empty by this very migration, so there is no
   row for any key to resolve to. Rather than invent placeholder nodes to
   preserve strings whose meaning nothing can yet interpret, the column is
   dropped and the values are re-granted through the control plane, where each
   grant gets the validity window and certificate reference §15.3 and §17
   actually need. Stated here rather than discovered from a diff.
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "dbd7ca971688"
down_revision: str | None = "69df6db2b72e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # -- Business calendars (§13.4, §27.2) ---------------------------------
    op.create_table(
        "business_calendars",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "working_hours",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("is_continuous", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_business_calendars_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_calendars")),
        sa.UniqueConstraint("tenant_id", "code", name="uq_business_calendars_tenant_id_code"),
    )
    op.create_index(
        op.f("ix_business_calendars_tenant_id"), "business_calendars", ["tenant_id"], unique=False
    )
    # One default per tenant, enforced by a partial unique index. Two concurrent
    # onboarding requests each see zero defaults and each set one; only the
    # database can refuse the second.
    op.create_index(
        "uq_business_calendars_tenant_id_default",
        "business_calendars",
        ["tenant_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )

    # -- Taxonomy (critique-log defect #1) --------------------------------
    op.create_table(
        "taxonomy_nodes",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("path", sa.String(length=520), nullable=False),
        sa.Column("depth", sa.Integer(), server_default="0", nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_selectable", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "severity_semantics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "routing_hints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "key ~ '^[a-z0-9][a-z0-9_.-]{0,62}[a-z0-9]$|^[a-z0-9]$'",
            name=op.f("ck_taxonomy_nodes_key_is_machine_safe"),
        ),
        sa.CheckConstraint(
            "depth >= 0 AND depth < 8", name=op.f("ck_taxonomy_nodes_depth_within_bound")
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id",
            name=op.f("ck_taxonomy_nodes_not_its_own_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["taxonomy_nodes.id"],
            name="fk_taxonomy_nodes_parent",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_taxonomy_nodes_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_nodes")),
        sa.UniqueConstraint("tenant_id", "key", name="uq_taxonomy_nodes_tenant_id_key"),
    )
    op.create_index(
        op.f("ix_taxonomy_nodes_tenant_id"), "taxonomy_nodes", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_taxonomy_nodes_tenant_id_parent_id",
        "taxonomy_nodes",
        ["tenant_id", "parent_id"],
        unique=False,
    )
    op.create_index(
        "ix_taxonomy_nodes_tenant_id_path", "taxonomy_nodes", ["tenant_id", "path"], unique=False
    )

    op.create_table(
        "taxonomy_prompt_sets",
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(length=35), nullable=False),
        sa.Column("encoder", sa.String(length=32), nullable=False),
        sa.Column("prompts", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "negative_prompts", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("prompt_set_version", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "cardinality(prompts) > 0", name=op.f("ck_taxonomy_prompt_sets_prompt_set_is_not_empty")
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["taxonomy_nodes.id"],
            name="fk_taxonomy_prompt_sets_node",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_taxonomy_prompt_sets_tenant",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxonomy_prompt_sets")),
        sa.UniqueConstraint(
            "tenant_id",
            "node_id",
            "locale",
            "encoder",
            name="uq_taxonomy_prompt_sets_tenant_id_node_id_locale_encoder",
        ),
    )
    op.create_index(
        op.f("ix_taxonomy_prompt_sets_tenant_id"),
        "taxonomy_prompt_sets",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_taxonomy_prompt_sets_tenant_id_node_id",
        "taxonomy_prompt_sets",
        ["tenant_id", "node_id"],
        unique=False,
    )

    # -- Translations -------------------------------------------------------
    op.create_table(
        "translations",
        sa.Column("namespace", sa.String(length=32), nullable=False),
        sa.Column("message_key", sa.String(length=128), nullable=False),
        sa.Column("locale", sa.String(length=35), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_translations_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_translations")),
        sa.UniqueConstraint(
            "tenant_id",
            "namespace",
            "message_key",
            "locale",
            name="uq_translations_tenant_id_namespace_message_key_locale",
        ),
    )
    op.create_index(op.f("ix_translations_tenant_id"), "translations", ["tenant_id"], unique=False)
    op.create_index(
        "ix_translations_tenant_id_namespace_locale",
        "translations",
        ["tenant_id", "namespace", "locale"],
        unique=False,
    )

    # -- Zones: the hierarchy of place ------------------------------------
    op.create_table(
        "zones",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=64), server_default="zone", nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("path", sa.String(length=650), nullable=False),
        sa.Column("depth", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "boundary",
            geoalchemy2.types.Geography(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column(
            "centroid",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), server_default="0", nullable=False),
        sa.CheckConstraint("depth >= 0 AND depth < 10", name=op.f("ck_zones_depth_within_bound")),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name=op.f("ck_zones_not_its_own_parent")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["zones.id"], name="fk_zones_parent", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_zones_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zones")),
        sa.UniqueConstraint("tenant_id", "code", name="uq_zones_tenant_id_code"),
    )
    op.create_index(
        "ix_zones_boundary", "zones", ["boundary"], unique=False, postgresql_using="gist"
    )
    op.create_index(op.f("ix_zones_parent_id"), "zones", ["parent_id"], unique=False)
    op.create_index(op.f("ix_zones_tenant_id"), "zones", ["tenant_id"], unique=False)
    op.create_index("ix_zones_tenant_id_path", "zones", ["tenant_id", "path"], unique=False)

    # -- Calendar exceptions ----------------------------------------------
    op.create_table(
        "calendar_exceptions",
        sa.Column("calendar_id", sa.UUID(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("is_working", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sla_multiplier", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(is_working AND sla_multiplier IS NOT NULL) "
            "OR (NOT is_working AND sla_multiplier IS NULL)",
            name=op.f("ck_calendar_exceptions_multiplier_belongs_to_working_spans"),
        ),
        sa.CheckConstraint(
            "ends_on >= starts_on", name=op.f("ck_calendar_exceptions_span_is_ordered")
        ),
        sa.CheckConstraint(
            "sla_multiplier IS NULL OR (sla_multiplier > 0 AND sla_multiplier <= 10.000)",
            name=op.f("ck_calendar_exceptions_multiplier_within_bound"),
        ),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["business_calendars.id"],
            name="fk_calendar_exceptions_calendar",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_calendar_exceptions_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_exceptions")),
    )
    op.create_index(
        op.f("ix_calendar_exceptions_tenant_id"), "calendar_exceptions", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_calendar_exceptions_tenant_id_calendar_id_starts_on",
        "calendar_exceptions",
        ["tenant_id", "calendar_id", "starts_on"],
        unique=False,
    )

    # -- Contractor certification scopes ----------------------------------
    op.create_table(
        "contractor_certifications",
        sa.Column("contractor_id", sa.UUID(), nullable=False),
        sa.Column("taxonomy_node_id", sa.UUID(), nullable=False),
        sa.Column("certificate_ref", sa.String(length=128), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from",
            name=op.f("ck_contractor_certifications_validity_span_is_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["contractor_id"],
            ["contractors.id"],
            name="fk_contractor_certifications_contractor",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_node_id"],
            ["taxonomy_nodes.id"],
            name="fk_contractor_certifications_node",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_contractor_certifications_tenant",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contractor_certifications")),
        sa.UniqueConstraint(
            "tenant_id",
            "contractor_id",
            "taxonomy_node_id",
            name="uq_contractor_certifications_scope",
        ),
    )
    op.create_index(
        op.f("ix_contractor_certifications_tenant_id"),
        "contractor_certifications",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_contractor_certifications_tenant_id_taxonomy_node_id",
        "contractor_certifications",
        ["tenant_id", "taxonomy_node_id"],
        unique=False,
    )

    # -- Shifts -------------------------------------------------------------
    op.create_table(
        "shifts",
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("weekdays", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column("starts_at", sa.Time(), nullable=False),
        sa.Column("ends_at", sa.Time(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cardinality(weekdays) > 0", name=op.f("ck_shifts_shift_covers_a_day")),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from",
            name=op.f("ck_shifts_effective_span_is_ordered"),
        ),
        sa.CheckConstraint(
            "weekdays <@ ARRAY[1,2,3,4,5,6,7]", name=op.f("ck_shifts_weekdays_are_iso")
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], name="fk_shifts_department", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_shifts_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shifts")),
        sa.UniqueConstraint(
            "tenant_id", "department_id", "code", name="uq_shifts_tenant_id_department_id_code"
        ),
    )
    op.create_index(op.f("ix_shifts_tenant_id"), "shifts", ["tenant_id"], unique=False)
    op.create_index(
        "ix_shifts_tenant_id_department_id", "shifts", ["tenant_id", "department_id"], unique=False
    )

    # -- departments becomes the arbitrary responsibility tree -------------
    op.add_column(
        "departments",
        sa.Column("kind", sa.String(length=64), server_default="department", nullable=False),
    )
    # Nullable, then backfilled, then NOT NULL. See the module docstring: the
    # autogenerated single-statement form fails on any table that already has
    # rows, which is every deployment that has onboarded a customer.
    op.add_column("departments", sa.Column("path", sa.String(length=650), nullable=True))
    op.add_column(
        "departments", sa.Column("depth", sa.Integer(), server_default="0", nullable=False)
    )
    op.execute("UPDATE departments SET path = code, depth = 0 WHERE path IS NULL")
    op.alter_column("departments", "path", nullable=False)

    op.add_column(
        "departments",
        sa.Column("is_assignable", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "departments", sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False)
    )
    op.add_column("departments", sa.Column("calendar_id", sa.UUID(), nullable=True))
    op.add_column(
        "departments",
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "departments", sa.Column("version", sa.BigInteger(), server_default="0", nullable=False)
    )
    op.create_index(
        "ix_departments_tenant_id_path", "departments", ["tenant_id", "path"], unique=False
    )
    op.create_foreign_key(
        "fk_departments_calendar",
        "departments",
        "business_calendars",
        ["calendar_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        op.f("ck_departments_depth_within_bound"), "departments", "depth >= 0 AND depth < 10"
    )
    op.create_check_constraint(
        op.f("ck_departments_not_its_own_parent"),
        "departments",
        "parent_id IS NULL OR parent_id <> id",
    )

    # See the module docstring: these values cannot be carried into
    # `contractor_certifications`, because the taxonomy they name is created
    # empty by this migration.
    op.drop_column("contractors", "categories_certified")

    # -- Tenant provenance and taxonomy revision --------------------------
    op.add_column(
        "tenants", sa.Column("provisioned_from_template", sa.String(length=64), nullable=True)
    )
    op.add_column("tenants", sa.Column("template_version", sa.String(length=32), nullable=True))
    op.add_column(
        "tenants", sa.Column("taxonomy_revision", sa.Integer(), server_default="0", nullable=False)
    )


def downgrade() -> None:
    op.drop_column("tenants", "taxonomy_revision")
    op.drop_column("tenants", "template_version")
    op.drop_column("tenants", "provisioned_from_template")

    op.add_column(
        "contractors",
        sa.Column(
            "categories_certified",
            postgresql.ARRAY(sa.TEXT()),
            server_default=sa.text("'{}'::text[]"),
            autoincrement=False,
            nullable=False,
        ),
    )

    op.drop_constraint(op.f("ck_departments_not_its_own_parent"), "departments", type_="check")
    op.drop_constraint(op.f("ck_departments_depth_within_bound"), "departments", type_="check")
    op.drop_constraint("fk_departments_calendar", "departments", type_="foreignkey")
    op.drop_index("ix_departments_tenant_id_path", table_name="departments")
    op.drop_column("departments", "version")
    op.drop_column("departments", "attributes")
    op.drop_column("departments", "calendar_id")
    op.drop_column("departments", "is_active")
    op.drop_column("departments", "is_assignable")
    op.drop_column("departments", "depth")
    op.drop_column("departments", "path")
    op.drop_column("departments", "kind")

    op.drop_index("ix_shifts_tenant_id_department_id", table_name="shifts")
    op.drop_index(op.f("ix_shifts_tenant_id"), table_name="shifts")
    op.drop_table("shifts")

    op.drop_index(
        "ix_contractor_certifications_tenant_id_taxonomy_node_id",
        table_name="contractor_certifications",
    )
    op.drop_index(
        op.f("ix_contractor_certifications_tenant_id"), table_name="contractor_certifications"
    )
    op.drop_table("contractor_certifications")

    op.drop_index(
        "ix_calendar_exceptions_tenant_id_calendar_id_starts_on", table_name="calendar_exceptions"
    )
    op.drop_index(op.f("ix_calendar_exceptions_tenant_id"), table_name="calendar_exceptions")
    op.drop_table("calendar_exceptions")

    op.drop_index("ix_zones_tenant_id_path", table_name="zones")
    op.drop_index(op.f("ix_zones_tenant_id"), table_name="zones")
    op.drop_index(op.f("ix_zones_parent_id"), table_name="zones")
    op.drop_index("ix_zones_boundary", table_name="zones", postgresql_using="gist")
    op.drop_table("zones")

    op.drop_index("ix_translations_tenant_id_namespace_locale", table_name="translations")
    op.drop_index(op.f("ix_translations_tenant_id"), table_name="translations")
    op.drop_table("translations")

    op.drop_index("ix_taxonomy_prompt_sets_tenant_id_node_id", table_name="taxonomy_prompt_sets")
    op.drop_index(op.f("ix_taxonomy_prompt_sets_tenant_id"), table_name="taxonomy_prompt_sets")
    op.drop_table("taxonomy_prompt_sets")

    op.drop_index("ix_taxonomy_nodes_tenant_id_path", table_name="taxonomy_nodes")
    op.drop_index("ix_taxonomy_nodes_tenant_id_parent_id", table_name="taxonomy_nodes")
    op.drop_index(op.f("ix_taxonomy_nodes_tenant_id"), table_name="taxonomy_nodes")
    op.drop_table("taxonomy_nodes")

    op.drop_index(
        "uq_business_calendars_tenant_id_default",
        table_name="business_calendars",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_index(op.f("ix_business_calendars_tenant_id"), table_name="business_calendars")
    op.drop_table("business_calendars")
