"""Phase 4 — public API, versioning & integration platform.

Revision ID: a41c9e5b7d02
Revises: dbd7ca971688
Create Date: 2026-08-17 14:00:00.000000

Five new tables and two altered columns on ``tenants``. Three things here were
not autogenerated and are the reason this file is written by hand:

1. **``webhook_cursor`` is seeded with its single row by the migration.** The
   table has a ``CHECK (id = 1)`` singleton constraint, and the dispatcher reads
   the row with ``FOR UPDATE`` rather than upserting it — an upsert would make
   two concurrent dispatchers each create-and-advance a position, which is
   exactly the double-delivery the cursor exists to prevent. So the row has to
   exist before the first dispatcher runs, and creating it here is the only
   place that is guaranteed to happen exactly once.

2. **``tenants.public_api_enabled`` defaults to false for existing rows.**
   Autogenerate would happily add a column whose server default matches the
   model; the point worth stating is that the *backfill* is the same value. A
   tenant provisioned before this migration never agreed to publish its
   aggregates, and inheriting a permissive default would turn a schema change
   into a disclosure.

3. **CheckConstraint names here are the *bare* names, not the prefixed ones.**
   ``Base.metadata`` carries a naming convention of
   ``ck_%(table_name)s_%(constraint_name)s``, and it applies to constraints
   declared in a migration exactly as it does to ones declared on a model.
   Writing the already-prefixed name produced
   ``ck_api_keys_ck_api_keys_quota_is_positive`` — and, on the longer ones,
   a name Postgres truncated at 63 characters, which is a constraint a later
   migration cannot reference by name. Caught by ``alembic check`` reporting
   drift between the model and the migrated schema, which is that check
   earning its place.

4. **The partial indexes carry their ``postgresql_where`` in both directions.**
   ``drop_index`` on a partial index without the predicate succeeds on some
   versions and leaves a differently-named artefact on others; restating it
   keeps ``downgrade()`` genuinely reversible, which is what
   ``nem rollback`` asserts.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a41c9e5b7d02"
down_revision: str | None = "dbd7ca971688"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # -- Tenant opt-in for the §16.3 public surface ------------------------
    op.add_column(
        "tenants",
        sa.Column("public_api_enabled", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "tenants",
        sa.Column("public_api_min_aggregate", sa.Integer(), server_default="5", nullable=False),
    )

    # -- API keys ----------------------------------------------------------
    op.create_table(
        "api_keys",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("key_prefix", sa.String(length=12), nullable=False),
        sa.Column("key_digest", sa.String(length=64), nullable=False),
        sa.Column("scopes", sa.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("quota_per_hour", sa.Integer(), server_default="3600", nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(key_digest) = 64", name="digest_is_a_sha256_hex"),
        sa.CheckConstraint("quota_per_hour > 0", name="quota_is_positive"),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoked_at >= created_at",
            name="revocation_follows_creation",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_api_keys_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_api_keys"),
        sa.UniqueConstraint("key_digest", name="uq_api_keys_key_digest"),
    )
    op.create_index(op.f("ix_api_keys_tenant_id"), "api_keys", ["tenant_id"])
    op.create_index("ix_api_keys_tenant_id_prefix", "api_keys", ["tenant_id", "key_prefix"])

    # -- Usage rollup ------------------------------------------------------
    op.create_table(
        "api_key_usage",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("api_key_id", sa.UUID(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("endpoint", sa.String(length=128), nullable=False),
        sa.Column("request_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("error_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("throttled_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["api_keys.id"], name="fk_api_key_usage_api_key", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_api_key_usage_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_api_key_usage"),
        sa.UniqueConstraint(
            "tenant_id", "api_key_id", "usage_date", "endpoint", name="uq_api_key_usage_bucket"
        ),
    )
    op.create_index(op.f("ix_api_key_usage_tenant_id"), "api_key_usage", ["tenant_id"])
    op.create_index(
        "ix_api_key_usage_tenant_id_usage_date", "api_key_usage", ["tenant_id", "usage_date"]
    )

    # -- Webhook subscriptions --------------------------------------------
    op.create_table(
        "webhook_endpoints",
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("secret_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("secret_fingerprint", sa.String(length=12), nullable=False),
        sa.Column("event_types", sa.ARRAY(sa.String(length=128)), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_reason", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cardinality(event_types) > 0", name="subscribes_to_something"),
        sa.CheckConstraint("secret_version >= 1", name="secret_version_is_positive"),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_webhook_endpoints_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_webhook_endpoints"),
        sa.UniqueConstraint("tenant_id", "url", name="uq_webhook_endpoints_tenant_id_url"),
    )
    op.create_index(op.f("ix_webhook_endpoints_tenant_id"), "webhook_endpoints", ["tenant_id"])
    op.create_index(
        "ix_webhook_endpoints_active",
        "webhook_endpoints",
        ["tenant_id"],
        postgresql_where=sa.text("is_active"),
    )

    # -- Delivery log ------------------------------------------------------
    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("endpoint_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("event_recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("attempts", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status_code", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'delivered', 'failed')",
            name="status_is_known",
        ),
        sa.CheckConstraint("attempts >= 0", name="attempts_non_negative"),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["webhook_endpoints.id"],
            name="fk_webhook_deliveries_endpoint",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_webhook_deliveries_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_webhook_deliveries"),
        sa.UniqueConstraint(
            "tenant_id", "endpoint_id", "event_id", name="uq_webhook_deliveries_endpoint_event"
        ),
    )
    op.create_index(op.f("ix_webhook_deliveries_tenant_id"), "webhook_deliveries", ["tenant_id"])
    op.create_index(
        "ix_webhook_deliveries_due",
        "webhook_deliveries",
        ["next_attempt_at"],
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_webhook_deliveries_tenant_id_endpoint_id_created_at",
        "webhook_deliveries",
        ["tenant_id", "endpoint_id", "created_at"],
    )

    # -- Fan-out cursor ----------------------------------------------------
    op.create_table(
        "webhook_cursor",
        sa.Column("id", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("last_outbox_id", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name="cursor_is_a_singleton"),
        sa.PrimaryKeyConstraint("id", name="pk_webhook_cursor"),
    )
    # The singleton row. See the module docstring: the dispatcher locks this row
    # rather than upserting it, so it must exist before the first run.
    #
    # ``last_outbox_id`` starts at the *current* outbox high-water mark, not at
    # zero. A deployment that has been running for months would otherwise
    # replay its entire history to the first webhook subscription anybody
    # creates — thousands of deliveries describing events from before the
    # subscriber existed, which is not a backfill, it is a flood.
    op.execute(
        "INSERT INTO webhook_cursor (id, last_outbox_id) "
        "VALUES (1, COALESCE((SELECT max(id) FROM outbox_messages), 0))"
    )


def downgrade() -> None:
    op.drop_table("webhook_cursor")

    op.drop_index(
        "ix_webhook_deliveries_tenant_id_endpoint_id_created_at", table_name="webhook_deliveries"
    )
    op.drop_index(
        "ix_webhook_deliveries_due",
        table_name="webhook_deliveries",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_webhook_deliveries_tenant_id"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")

    op.drop_index(
        "ix_webhook_endpoints_active",
        table_name="webhook_endpoints",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(op.f("ix_webhook_endpoints_tenant_id"), table_name="webhook_endpoints")
    op.drop_table("webhook_endpoints")

    op.drop_index("ix_api_key_usage_tenant_id_usage_date", table_name="api_key_usage")
    op.drop_index(op.f("ix_api_key_usage_tenant_id"), table_name="api_key_usage")
    op.drop_table("api_key_usage")

    op.drop_index("ix_api_keys_tenant_id_prefix", table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_tenant_id"), table_name="api_keys")
    op.drop_table("api_keys")

    op.drop_column("tenants", "public_api_min_aggregate")
    op.drop_column("tenants", "public_api_enabled")
