"""Phase 2 — event store, schema registry and tenancy.

The Blueprint §9.2 schema, with ``tenant_id`` on every domain table from the
first migration rather than added later. Retrofitting tenancy is a rewrite, so
there is no migration in this repository's future that adds it.

Three things autogenerate cannot produce, added by hand:

1. **Extensions.** ``CREATE EXTENSION IF NOT EXISTS`` for the four this schema
   depends on, so a fresh database migrates without a separate bootstrap step.
   The downgrade deliberately does *not* drop them: PostGIS owns
   ``spatial_ref_sys`` and dropping it destroys reference data this migration
   never created, which is not a reversal, it is collateral damage.
2. **Partitions.** ``events`` is declared ``PARTITION BY RANGE (recorded_at)``,
   and a partitioned table with no partitions rejects every insert. A DEFAULT
   partition is created as the safety net and a five-month window around the
   migration date as the real storage, after which
   ``nemesis.events.partitions`` keeps the window ahead of the clock.
3. **The vector and geography imports** the autogenerated header omits.

Reversibility is tested, not assumed: ``upgrade → downgrade → upgrade`` runs in
CI, and dropping the partitioned parent drops its partitions with it.

Revision ID: 5347db8d1387
Revises:
Create Date: 2026-08-16 11:59:08.716525

"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "5347db8d1387"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# postgis     — geography(POINT, 4326) on complaints and clusters
# vector      — vector(384) text and halfvec(512) image embeddings
# pgcrypto    — gen_random_uuid() as the server-side primary key default
# pg_trgm     — Phase 17 fuzzy matching over contractor address/phone/directors
REQUIRED_EXTENSIONS = ("postgis", "vector", "pgcrypto", "pg_trgm")

# Months created ahead of the migration date. The maintenance job extends this
# continuously; the window exists so a stack that is started and immediately
# written to never touches the DEFAULT partition.
INITIAL_PARTITION_MONTHS = 5


def upgrade() -> None:
    for extension in REQUIRED_EXTENSIONS:
        op.execute(f"CREATE EXTENSION IF NOT EXISTS {extension}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archived_partitions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("partition_name", sa.String(length=128), nullable=False),
        sa.Column("range_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("range_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("row_count", sa.BigInteger(), nullable=False),
        sa.Column("archive_location", sa.Text(), nullable=True),
        sa.Column("archive_digest", sa.String(length=64), nullable=True),
        sa.Column(
            "detached_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_archived_partitions")),
        sa.UniqueConstraint("partition_name", name=op.f("uq_archived_partitions_partition_name")),
    )
    op.create_table(
        "tenants",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("plan", sa.String(length=64), server_default="pilot", nullable=False),
        sa.Column("primary_locale", sa.String(length=35), server_default="en", nullable=False),
        sa.Column(
            "locales", postgresql.ARRAY(sa.String(length=35)), server_default="{en}", nullable=False
        ),
        sa.Column("timezone", sa.String(length=64), server_default="Asia/Kolkata", nullable=False),
        sa.Column("data_residency", sa.String(length=32), server_default="in", nullable=False),
        sa.Column(
            "branding", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "budget_allocations",
        sa.Column("ward", sa.String(length=128), nullable=True),
        sa.Column("funding_source", sa.String(length=128), nullable=False),
        sa.Column("fiscal_year", sa.String(length=16), nullable=False),
        sa.Column("allocated_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column(
            "spent_amount", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_budget_allocations_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_allocations")),
    )
    op.create_index(
        op.f("ix_budget_allocations_tenant_id"), "budget_allocations", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_budget_allocations_tenant_id_ward_fiscal_year",
        "budget_allocations",
        ["tenant_id", "ward", "fiscal_year"],
        unique=False,
    )
    op.create_table(
        "complaint_clusters",
        sa.Column(
            "centroid",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("report_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("first_reported", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_reported", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_severity", sa.Float(), nullable=True),
        sa.Column("superseded_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["complaint_clusters.id"],
            name="fk_clusters_superseded_by",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_complaint_clusters_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_clusters")),
    )
    op.create_index(
        "ix_complaint_clusters_centroid",
        "complaint_clusters",
        ["centroid"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_complaint_clusters_tenant_id"), "complaint_clusters", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_complaint_clusters_tenant_id_last_reported",
        "complaint_clusters",
        ["tenant_id", "last_reported"],
        unique=False,
    )
    op.create_table(
        "contractors",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("registration_id", sa.String(length=128), nullable=False),
        sa.Column("registered_address", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column(
            "director_names", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "categories_certified", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("active_since", sa.Date(), nullable=True),
        sa.Column(
            "computed_rating",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_contractors_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contractors")),
        sa.UniqueConstraint(
            "tenant_id", "registration_id", name="uq_contractors_tenant_id_registration_id"
        ),
    )
    op.create_index(op.f("ix_contractors_tenant_id"), "contractors", ["tenant_id"], unique=False)
    op.create_table(
        "departments",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("ward", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["departments.id"], name="fk_departments_parent", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_departments_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("tenant_id", "code", name="uq_departments_tenant_id_code"),
    )
    op.create_index(op.f("ix_departments_parent_id"), "departments", ["parent_id"], unique=False)
    op.create_index(op.f("ix_departments_tenant_id"), "departments", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_departments_ward"), "departments", ["ward"], unique=False)
    op.create_table(
        "event_chain_heads",
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("head_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "sequence >= 0", name=op.f("ck_event_chain_heads_sequence_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_event_chain_heads_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "entity_type", "entity_id", name="pk_event_chain_heads"
        ),
    )
    op.create_index(
        op.f("ix_event_chain_heads_tenant_id"), "event_chain_heads", ["tenant_id"], unique=False
    )
    op.create_table(
        "event_idempotency",
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("event_recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_event_idempotency_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "idempotency_key", name="pk_event_idempotency"),
    )
    op.create_index(
        op.f("ix_event_idempotency_tenant_id"), "event_idempotency", ["tenant_id"], unique=False
    )
    op.create_table(
        "event_snapshots",
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("projector_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_event_snapshots_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_snapshots")),
        sa.UniqueConstraint(
            "tenant_id",
            "entity_type",
            "entity_id",
            "sequence",
            name="uq_event_snapshots_entity_sequence",
        ),
    )
    op.create_index(
        "ix_event_snapshots_lookup",
        "event_snapshots",
        ["tenant_id", "entity_type", "entity_id", "sequence"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_snapshots_tenant_id"), "event_snapshots", ["tenant_id"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("event_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_role", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("causation_event_id", sa.BigInteger(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("event_version >= 1", name=op.f("ck_events_version_positive")),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_events_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_events_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", "recorded_at", name="pk_events"),
        sa.UniqueConstraint(
            "tenant_id",
            "entity_type",
            "entity_id",
            "sequence",
            "recorded_at",
            name="uq_events_entity_sequence",
        ),
        postgresql_partition_by="RANGE (recorded_at)",
    )
    op.create_index("ix_events_correlation_id", "events", ["correlation_id"], unique=False)
    op.create_index(
        "ix_events_entity",
        "events",
        ["tenant_id", "entity_type", "entity_id", "sequence"],
        unique=False,
    )
    op.create_index(op.f("ix_events_tenant_id"), "events", ["tenant_id"], unique=False)
    op.create_index(
        "ix_events_type_time", "events", ["tenant_id", "event_type", "recorded_at"], unique=False
    )
    op.create_table(
        "complaints",
        sa.Column("status", sa.String(length=32), server_default="submitted", nullable=False),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("classification_confidence", sa.Float(), nullable=True),
        sa.Column("description_text", sa.Text(), nullable=True),
        sa.Column("photo_url", sa.Text(), nullable=True),
        sa.Column("audio_url", sa.Text(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "exif_location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("text_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("image_embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=512), nullable=True),
        sa.Column("cluster_id", sa.UUID(), nullable=True),
        sa.Column("severity_score", sa.Float(), nullable=True),
        sa.Column("severity_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("severity_policy_version", sa.String(length=64), nullable=True),
        sa.Column("ward", sa.String(length=128), nullable=True),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("submitter_device_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("is_safety_flagged", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_fraud_flagged", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("funding_source", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["complaint_clusters.id"],
            name="fk_complaints_cluster",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name="fk_complaints_department",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_complaints_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaints")),
    )
    op.create_index(op.f("ix_complaints_category"), "complaints", ["category"], unique=False)
    op.create_index(
        "ix_complaints_image_embedding_hnsw",
        "complaints",
        ["image_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 128},
        postgresql_ops={"image_embedding": "halfvec_cosine_ops"},
    )
    op.create_index(
        "ix_complaints_location", "complaints", ["location"], unique=False, postgresql_using="gist"
    )
    op.create_index(op.f("ix_complaints_tenant_id"), "complaints", ["tenant_id"], unique=False)
    op.create_index(
        "ix_complaints_tenant_id_cluster_id",
        "complaints",
        ["tenant_id", "cluster_id"],
        unique=False,
    )
    op.create_index(
        "ix_complaints_tenant_id_reported_at",
        "complaints",
        ["tenant_id", "reported_at"],
        unique=False,
    )
    op.create_index(
        "ix_complaints_tenant_id_status", "complaints", ["tenant_id", "status"], unique=False
    )
    op.create_index(
        "ix_complaints_text_embedding_hnsw",
        "complaints",
        ["text_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 128},
        postgresql_ops={"text_embedding": "vector_cosine_ops"},
    )
    op.create_index(op.f("ix_complaints_ward"), "complaints", ["ward"], unique=False)
    op.create_table(
        "users",
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("contractor_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contractor_id"], ["contractors.id"], name="fk_users_contractor", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], name="fk_users_department", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_users_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("tenant_id", "subject", name="uq_users_tenant_id_subject"),
    )
    op.create_index(op.f("ix_users_contractor_id"), "users", ["contractor_id"], unique=False)
    op.create_index(op.f("ix_users_department_id"), "users", ["department_id"], unique=False)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "work_orders",
        sa.Column("complaint_cluster_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("assigned_to_type", sa.String(length=32), nullable=True),
        sa.Column("assigned_to_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="created", nullable=False),
        sa.Column("sla_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sla_policy_version", sa.String(length=64), nullable=True),
        sa.Column("budgeted_cost", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("actual_cost", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("fund_released", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("before_photo_url", sa.Text(), nullable=True),
        sa.Column("after_photo_url", sa.Text(), nullable=True),
        sa.Column("ssim_score", sa.Float(), nullable=True),
        sa.Column("milestone_stage", sa.String(length=32), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.BigInteger(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["complaint_cluster_id"],
            ["complaint_clusters.id"],
            name="fk_work_orders_cluster",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name="fk_work_orders_department",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_work_orders_tenant", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_orders")),
    )
    op.create_index(
        op.f("ix_work_orders_complaint_cluster_id"),
        "work_orders",
        ["complaint_cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_orders_department_id"), "work_orders", ["department_id"], unique=False
    )
    op.create_index(op.f("ix_work_orders_tenant_id"), "work_orders", ["tenant_id"], unique=False)
    op.create_index(
        "ix_work_orders_tenant_id_sla_deadline",
        "work_orders",
        ["tenant_id", "sla_deadline"],
        unique=False,
    )
    op.create_index(
        "ix_work_orders_tenant_id_status", "work_orders", ["tenant_id", "status"], unique=False
    )
    # ### end Alembic commands ###

    _create_event_partitions()


def _create_event_partitions() -> None:
    """Give the partitioned ``events`` table somewhere to put rows.

    The DEFAULT partition is created **first and always**. Without it, an insert
    whose ``recorded_at`` falls outside every declared range is rejected — so a
    maintenance job that fails to run for a month would turn into a total outage
    of the write path, on an append-only log, with no way to record that it
    happened. A default partition converts that failure into a performance
    problem and an alert.

    Its cost is that attaching a partition for a range that already has rows in
    DEFAULT requires a full scan and an exclusive lock. That is why the window
    below is created up front and kept ahead by
    ``nemesis.events.partitions.ensure_partitions`` — the default is designed to
    stay empty, and ``NemesisEventDefaultPartitionNonEmpty`` alerts if it ever
    is not.
    """
    op.execute("CREATE TABLE IF NOT EXISTS events_default PARTITION OF events DEFAULT")
    op.execute(
        f"""
        DO $$
        DECLARE
            first_month date := date_trunc('month', now() - interval '1 month')::date;
            month_start date;
        BEGIN
            FOR offset_months IN 0..{INITIAL_PARTITION_MONTHS - 1} LOOP
                month_start := (first_month + (offset_months || ' month')::interval)::date;
                EXECUTE format(
                    'CREATE TABLE IF NOT EXISTS %I PARTITION OF events '
                    'FOR VALUES FROM (%L) TO (%L)',
                    'events_' || to_char(month_start, 'YYYY_MM'),
                    month_start,
                    (month_start + interval '1 month')::date
                );
            END LOOP;
        END $$;
        """
    )


def downgrade() -> None:
    # Dropping the partitioned parent drops every partition with it, so the
    # partitions created above need no explicit teardown. Extensions are left
    # in place on purpose — see the module docstring.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_work_orders_tenant_id_status", table_name="work_orders")
    op.drop_index("ix_work_orders_tenant_id_sla_deadline", table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_tenant_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_department_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_complaint_cluster_id"), table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_department_id"), table_name="users")
    op.drop_index(op.f("ix_users_contractor_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_complaints_ward"), table_name="complaints")
    op.drop_index(
        "ix_complaints_text_embedding_hnsw",
        table_name="complaints",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 128},
        postgresql_ops={"text_embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_complaints_tenant_id_status", table_name="complaints")
    op.drop_index("ix_complaints_tenant_id_reported_at", table_name="complaints")
    op.drop_index("ix_complaints_tenant_id_cluster_id", table_name="complaints")
    op.drop_index(op.f("ix_complaints_tenant_id"), table_name="complaints")
    op.drop_index("ix_complaints_location", table_name="complaints", postgresql_using="gist")
    op.drop_index(
        "ix_complaints_image_embedding_hnsw",
        table_name="complaints",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 128},
        postgresql_ops={"image_embedding": "halfvec_cosine_ops"},
    )
    op.drop_index(op.f("ix_complaints_category"), table_name="complaints")
    op.drop_table("complaints")
    op.drop_index("ix_events_type_time", table_name="events")
    op.drop_index(op.f("ix_events_tenant_id"), table_name="events")
    op.drop_index("ix_events_entity", table_name="events")
    op.drop_index("ix_events_correlation_id", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_event_snapshots_tenant_id"), table_name="event_snapshots")
    op.drop_index("ix_event_snapshots_lookup", table_name="event_snapshots")
    op.drop_table("event_snapshots")
    op.drop_index(op.f("ix_event_idempotency_tenant_id"), table_name="event_idempotency")
    op.drop_table("event_idempotency")
    op.drop_index(op.f("ix_event_chain_heads_tenant_id"), table_name="event_chain_heads")
    op.drop_table("event_chain_heads")
    op.drop_index(op.f("ix_departments_ward"), table_name="departments")
    op.drop_index(op.f("ix_departments_tenant_id"), table_name="departments")
    op.drop_index(op.f("ix_departments_parent_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_contractors_tenant_id"), table_name="contractors")
    op.drop_table("contractors")
    op.drop_index("ix_complaint_clusters_tenant_id_last_reported", table_name="complaint_clusters")
    op.drop_index(op.f("ix_complaint_clusters_tenant_id"), table_name="complaint_clusters")
    op.drop_index(
        "ix_complaint_clusters_centroid", table_name="complaint_clusters", postgresql_using="gist"
    )
    op.drop_table("complaint_clusters")
    op.drop_index(
        "ix_budget_allocations_tenant_id_ward_fiscal_year", table_name="budget_allocations"
    )
    op.drop_index(op.f("ix_budget_allocations_tenant_id"), table_name="budget_allocations")
    op.drop_table("budget_allocations")
    op.drop_table("tenants")
    op.drop_table("archived_partitions")
    # ### end Alembic commands ###
