"""The developer portal, bulk export, and version discovery.

**The reference is generated, never written.** FastAPI already produces an
OpenAPI document from the code, and this serves a rendered view of it. A
hand-written reference is a second description of the same contract, and the two
diverge on the first change nobody remembered to mirror — at which point the
documentation is worse than none, because a consumer trusts it.

**The portal is served as HTML from this process rather than as a static site.**
There is no CDN, no build step, and no separate deployment to keep in sync; the
page a consumer reads is generated by the same build that serves the API, so it
cannot describe a version this deployment does not run. The page has no external
assets at all — a public accountability surface that fetches a font from a third
party leaks every reader's address to that third party.

**The sandbox is a real tenant with synthetic data.** Not a mocked response
path: a mock proves the shape and nothing about whether the query works, and the
integration that passes against a mock is the one that fails on first contact
with suppression, pagination, and empty buckets. The sandbox is provisioned
through the ordinary control plane and its data is generated, so an integrator
exercises the real code against rows no citizen submitted.
"""

from __future__ import annotations

import html
from datetime import UTC, datetime
from typing import Annotated, Final

from fastapi import APIRouter, Query, Request, Response
from fastapi.responses import HTMLResponse, StreamingResponse
from pydantic import BaseModel, ConfigDict

from nemesis.api.deps import ConfigDep, SessionDep
from nemesis.api.errors import HTTP_422_UNPROCESSABLE, PROBLEM_BASE, ProblemDetailError
from nemesis.api.key_deps import KeyDep
from nemesis.api.versioning import (
    PUBLIC_API_NOTICE_DAYS,
    all_versions,
    current_version,
    sunset_notice_remaining,
)
from nemesis.integrations import keys, webhooks
from nemesis.public import export

#: Versioned endpoints — discovery and export live under /api/v1 like everything
#: else, because both are contracts a consumer integrates against.
router = APIRouter(tags=["developers"])

#: The portal itself is mounted at the *root*, unversioned. It is a page for a
#: human, not a contract for a client, and the ``Link rel="deprecation"`` header
#: on a sunset v1 response has to point somewhere that outlives v1 — a
#: deprecation notice hosted inside the deprecated version is a note left in the
#: building being demolished.
portal_router = APIRouter(tags=["developers"], include_in_schema=False)


class ApiModel(BaseModel):
    model_config = ConfigDict(frozen=True)


class VersionResponse(ApiModel):
    name: str
    status: str
    released_on: str
    deprecated_on: str | None
    sunset_on: str | None
    successor: str | None
    days_until_sunset: int | None
    description: str


class VersionsResponse(ApiModel):
    current: str
    notice_period_days: int
    policy: str
    versions: list[VersionResponse]


@router.get("/versions", summary="Published API versions and their deprecation clock")
async def versions() -> VersionsResponse:
    """Machine-readable version discovery.

    A consumer that polls this can warn its own operators months before a sunset
    without anybody reading a changelog — which is the difference between a
    published clock and an announced one.
    """
    today = datetime.now(tz=UTC).date()
    return VersionsResponse(
        current=current_version().name,
        notice_period_days=PUBLIC_API_NOTICE_DAYS,
        policy=(
            f"A published API version is removed no sooner than {PUBLIC_API_NOTICE_DAYS} days "
            f"after its deprecation is announced. Deprecation and removal dates are carried "
            f"on every response as RFC 9745 'Deprecation' and RFC 8594 'Sunset' headers."
        ),
        versions=[
            VersionResponse(
                name=version.name,
                status=str(version.status),
                released_on=version.released_on.isoformat(),
                deprecated_on=(
                    None if version.deprecated_on is None else version.deprecated_on.isoformat()
                ),
                sunset_on=None if version.sunset_on is None else version.sunset_on.isoformat(),
                successor=version.successor,
                days_until_sunset=sunset_notice_remaining(version, today),
                description=version.description,
            )
            for version in all_versions()
        ],
    )


# ---------------------------------------------------------------------------
# Bulk export
# ---------------------------------------------------------------------------

_DATASETS: Final = {
    "complaints": export.COMPLAINT_COLUMNS,
    "work-orders": export.WORK_ORDER_COLUMNS,
}


@router.get(
    "/export/{dataset}",
    summary="Bulk extract for RTI applicants and researchers",
    response_class=StreamingResponse,
)
async def bulk_export(
    dataset: str,
    caller: KeyDep,
    session: SessionDep,
    settings: ConfigDep,
    fmt: Annotated[str, Query(alias="format")] = "csv",
    since: Annotated[datetime | None, Query()] = None,
    until: Annotated[datetime | None, Query()] = None,
) -> StreamingResponse:
    """Streamed CSV or NDJSON, scoped to the calling key's tenant.

    **Requires a key**, unlike the aggregate endpoints. Not because the rows are
    more sensitive — they go through the same scrub — but because a full-scan
    extract is a fundamentally different cost from a cached aggregate, and an
    unauthenticated full scan is a denial-of-service primitive anyone can fire.
    Issuing a key to a researcher is a conversation that takes a minute and gives
    them a quota; leaving it open gives everybody an unmetered table scan.
    """
    caller.require("export:read")

    columns = _DATASETS.get(dataset)
    if columns is None:
        raise ProblemDetailError(
            status_code=HTTP_422_UNPROCESSABLE,
            title="Unknown dataset",
            detail=f"Available datasets are {sorted(_DATASETS)}.",
            problem_type=f"{PROBLEM_BASE}/validation-error",
        )
    try:
        chosen = export.resolve_format(fmt)
    except export.UnknownFormatError as exc:
        raise ProblemDetailError(
            status_code=HTTP_422_UNPROCESSABLE,
            title="Unknown export format",
            detail=str(exc),
            problem_type=f"{PROBLEM_BASE}/validation-error",
        ) from exc

    limit = settings.public_api.max_export_rows
    tenant_id = caller.key.tenant_id
    rows = (
        export.complaint_rows(session, tenant_id=tenant_id, since=since, until=until, limit=limit)
        if dataset == "complaints"
        else export.work_order_rows(
            session, tenant_id=tenant_id, since=since, until=until, limit=limit
        )
    )

    stamp = datetime.now(tz=UTC).date().isoformat()
    return StreamingResponse(
        export.render(rows, fmt=chosen, columns=columns),
        media_type=chosen.media_type,
        headers={
            "Content-Disposition": (
                f'attachment; filename="nemesis-{dataset}-{stamp}.{chosen.extension}"'
            ),
            # The row cap is announced rather than silently applied. An extract
            # truncated at a hundred thousand rows without saying so is a
            # dataset a researcher will publish conclusions from.
            "X-Export-Row-Limit": str(limit),
            "Cache-Control": "no-store",
        },
    )


# ---------------------------------------------------------------------------
# Portal
# ---------------------------------------------------------------------------


@portal_router.get("/developers", response_class=HTMLResponse, include_in_schema=False)
async def portal(request: Request) -> Response:
    """The human-readable entry point. Generated from the same registries the API uses."""
    today = datetime.now(tz=UTC).date()
    version_rows = "".join(
        f"<tr><td><code>{html.escape(v.name)}</code></td>"
        f"<td>{html.escape(str(v.status))}</td>"
        f"<td>{v.released_on.isoformat()}</td>"
        f"<td>{'—' if v.sunset_on is None else v.sunset_on.isoformat()}</td>"
        f"<td>{html.escape(v.description)}</td></tr>"
        for v in all_versions()
    )
    scope_rows = "".join(
        f"<tr><td><code>{html.escape(name)}</code></td><td>{html.escape(why)}</td></tr>"
        for name, why in sorted(keys.SCOPES.items())
    )
    event_rows = "".join(
        f"<li><code>{html.escape(name)}</code></li>"
        for name in sorted(webhooks.known_event_types())
    )
    _ = today

    body = _PORTAL_TEMPLATE.format(
        base=html.escape(str(request.base_url).rstrip("/")),
        version_rows=version_rows,
        scope_rows=scope_rows,
        event_rows=event_rows,
        notice_days=PUBLIC_API_NOTICE_DAYS,
        tolerance=webhooks.RECOMMENDED_TOLERANCE_SECONDS,
        signature_header=html.escape(webhooks.SIGNATURE_HEADER),
        verify_source=html.escape(_VERIFY_EXAMPLE),
    )
    return HTMLResponse(content=body)


#: A worked verification example, in the reader's language rather than ours.
#:
#: Shipped because every integrator writes this function and most of them write
#: ``==`` instead of a constant-time comparison, which reintroduces the signature
#: forgery the scheme exists to prevent. ``integrations.webhooks.verify`` is the
#: same algorithm, executed by this repository's own test suite — so the example
#: on this page is one that has been run rather than one that was typed.
_VERIFY_EXAMPLE = """import hashlib, hmac, time

def verify(secret: str, body: bytes, header: str, tolerance: int = 300) -> bool:
    parts = dict(p.split("=", 1) for p in header.split(",") if "=" in p)
    issued, presented = int(parts["t"]), parts["v1"]
    if abs(int(time.time()) - issued) > tolerance:
        return False                      # replay outside the window
    expected = hmac.new(
        secret.encode(), f"{issued}.".encode() + body, hashlib.sha256
    ).hexdigest()
    return hmac.compare_digest(expected, presented)   # not ==
"""


_PORTAL_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>NEMESIS — Developer reference</title>
<style>
:root {{ color-scheme: light dark; --fg:#111; --bg:#fff; --muted:#555; --line:#d8d8d8;
         --code:#f5f5f5; }}
@media (prefers-color-scheme: dark) {{
  :root {{ --fg:#e8e8e8; --bg:#141414; --muted:#a8a8a8; --line:#333; --code:#1e1e1e; }}
}}
body {{ font: 16px/1.6 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
        color: var(--fg); background: var(--bg); margin: 0 auto; padding: 2rem 1.25rem;
        max-width: 52rem; }}
h1 {{ font-size: 1.6rem; margin-bottom: .25rem; }}
h2 {{ font-size: 1.15rem; margin-top: 2.5rem; border-bottom: 1px solid var(--line);
      padding-bottom: .3rem; }}
p.lede {{ color: var(--muted); margin-top: 0; }}
table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: .92rem; }}
th, td {{ text-align: left; padding: .45rem .6rem; border-bottom: 1px solid var(--line);
          vertical-align: top; }}
th {{ font-weight: 600; }}
code {{ background: var(--code); padding: .1rem .32rem; border-radius: 3px;
        font: .88em ui-monospace, SFMono-Regular, Menlo, monospace; }}
pre {{ background: var(--code); padding: .9rem 1rem; border-radius: 5px; overflow-x: auto; }}
pre code {{ background: none; padding: 0; }}
ul.cols {{ columns: 2; list-style: none; padding: 0; }}
.note {{ border-left: 3px solid var(--line); padding: .1rem 0 .1rem 1rem;
         color: var(--muted); }}
</style></head><body>

<h1>NEMESIS developer reference</h1>
<p class="lede">A read-only, rate-limited public API over privacy-scrubbed municipal
accountability data, plus signed outbound webhooks for partners.</p>

<h2>Start here</h2>
<ul>
  <li><a href="/docs">Interactive reference</a> — generated from the running build,
      so it cannot describe a version this deployment does not serve.</li>
  <li><a href="/openapi.json">OpenAPI document</a> — generate a client from it.</li>
  <li><a href="/api/v1/versions">Version discovery</a> — the deprecation clock,
      machine-readable.</li>
</ul>

<h2 id="versions">Versions and the deprecation clock</h2>
<p>A published version is removed no sooner than <strong>{notice_days} days</strong> after
its deprecation is announced. Every response carries <code>Deprecation</code> and
<code>Sunset</code> headers once a clock is running; a version past its sunset answers
<code>410 Gone</code>.</p>
<table><thead><tr><th>Version</th><th>Status</th><th>Released</th><th>Sunset</th>
<th>Notes</th></tr></thead><tbody>{version_rows}</tbody></table>
<p class="note">A version marked <code>preview</code> carries no compatibility promise
and may change. That is what preview means, and it is stated rather than implied so
nobody integrates against one expecting the twelve months.</p>

<h2>Public endpoints</h2>
<p>No authentication. Rate-limited per client address. Every organisation opts in
before any of its data is published, and aggregates below a suppression floor are
withheld with <code>"suppressed": true</code> rather than silently omitted — an
absent figure and a withheld one are different facts.</p>
<pre><code>GET {base}/api/v1/public/{{organisation}}/zones
GET {base}/api/v1/public/{{organisation}}/ward/{{zone_code}}/summary
GET {base}/api/v1/public/{{organisation}}/contractor/{{contractor_id}}/profile
GET {base}/api/v1/public/{{organisation}}/budget/{{zone_code}}?fiscal_year=2026-27</code></pre>
<p class="note">No response on this surface carries an exact coordinate, a complaint
identifier, a device fingerprint, or a citizen's own words. Coordinates are rounded to
three decimal places — roughly 110 metres, enough to place a pin on a street and not
enough to place it at a door.</p>

<h2>API keys</h2>
<p>A key raises your quota and unlocks bulk export. Send it as
<code>X-API-Key</code>. The secret is shown once at creation and is not recoverable —
it is stored as a digest, so a lost key is replaced, never retrieved.</p>
<table><thead><tr><th>Scope</th><th>Grants</th></tr></thead><tbody>{scope_rows}</tbody></table>

<h2>Bulk export</h2>
<pre><code>GET {base}/api/v1/export/complaints?format=csv&amp;since=2026-01-01T00:00:00Z
GET {base}/api/v1/export/work-orders?format=ndjson</code></pre>
<p>CSV and NDJSON. Responses stream, so a large extract does not wait on a
server-side assembly step. The row cap is returned in
<code>X-Export-Row-Limit</code>: a truncated extract always says it was truncated.</p>
<p class="note">Parquet is deliberately not offered. It is a columnar analytics format
whose value is a query engine, and its library is a large dependency in an image that
serves citizen submissions. See ADR-0024.</p>

<h2>Webhooks</h2>
<p>Signed with HMAC-SHA256 over <code>"&lt;timestamp&gt;.&lt;raw body&gt;"</code>, sent as
<code>{signature_header}: t=&lt;unix&gt;,v1=&lt;hex&gt;</code>. Verify against the
<em>raw</em> body before parsing it, and reject anything older than your tolerance
window — <strong>{tolerance} seconds</strong> is recommended. The timestamp is inside
the signed string, so it cannot be altered to replay an old delivery.</p>
<pre><code>{verify_source}</code></pre>
<p>Delivery is at-least-once. <code>X-Nemesis-Delivery</code> is stable across retries,
so deduplicate on it. A failing endpoint is retried on a schedule spanning more than
ten hours; one that fails continuously is disabled and the reason is recorded in the
delivery log you can read back.</p>

<h3>Subscribable event types</h3>
<ul class="cols">{event_rows}</ul>

<h2>Sandbox</h2>
<p>Ask for a sandbox organisation. It is a real tenant with generated data, exercising
the same code paths as production — including suppression and empty buckets, which is
where integrations written against a mock tend to break.</p>

</body></html>
"""
